name: projek_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.2
  http: ^1.1.0
  app_links: ^6.3.2
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.6
  url_launcher: ^6.1.10
  image_picker: ^1.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.5
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
