// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYYoBmpapnbsw4L-p7BWvJWYt5FZxNFu8',
    appId: '1:474454721171:web:032c21180b7176a42f0366',
    messagingSenderId: '474454721171',
    projectId: 'ngekos-app-project',
    authDomain: 'ngekos-app-project.firebaseapp.com',
    storageBucket: 'ngekos-app-project.firebasestorage.app',
    measurementId: 'G-K7ZE98PR4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC37Ab8-9Gxc9XCd3jPvTus8kV1EPM9yoE',
    appId: '1:474454721171:android:f5e9bff2c70d10172f0366',
    messagingSenderId: '474454721171',
    projectId: 'ngekos-app-project',
    storageBucket: 'ngekos-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAopTWo08L93Y-NiajY7GW0VOzU4JQluQA',
    appId: '1:474454721171:ios:4e4593b746096d1b2f0366',
    messagingSenderId: '474454721171',
    projectId: 'ngekos-app-project',
    storageBucket: 'ngekos-app-project.firebasestorage.app',
    iosBundleId: 'com.example.projekMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAopTWo08L93Y-NiajY7GW0VOzU4JQluQA',
    appId: '1:474454721171:ios:4e4593b746096d1b2f0366',
    messagingSenderId: '474454721171',
    projectId: 'ngekos-app-project',
    storageBucket: 'ngekos-app-project.firebasestorage.app',
    iosBundleId: 'com.example.projekMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYYoBmpapnbsw4L-p7BWvJWYt5FZxNFu8',
    appId: '1:474454721171:web:75af3acfa6c05fbe2f0366',
    messagingSenderId: '474454721171',
    projectId: 'ngekos-app-project',
    authDomain: 'ngekos-app-project.firebaseapp.com',
    storageBucket: 'ngekos-app-project.firebasestorage.app',
    measurementId: 'G-N94HYT6D74',
  );
}
